import Link from 'next/link';
import { BoardPreview } from '../components/board-preview';
import { HealthBadge } from '../components/health-badge';

const features = [
  { icon: '✦', title: 'Focused play', text: 'A calm foundation for thoughtful games.' },
  { icon: '◈', title: 'Reliable core', text: 'A clear API boundary from the first phase.' },
  { icon: '◉', title: 'Built to grow', text: 'Every phase adds a testable slice.' },
];

export default function HomePage() {
  return <main className="site-shell"><header className="topbar"><Link className="brand" href="/"><span className="brand-mark">♞</span><span>OMEGA<span>CHESS</span></span></Link><nav><a className="active" href="#play">Play</a><a href="/lobby">Lobby</a><a href="/auth">Register / Login</a><a href="#learn">Learn</a><a href="#roadmap">Roadmap</a></nav><div className="top-actions"><HealthBadge /><Link className="ghost-button" href="/play">Open board</Link></div></header><section className="hero page-width" id="play"><div className="hero-copy"><p className="eyebrow"><span className="pulse" /> Phase 4 · local realtime play</p><h1>Chess that leaves room for thought.</h1><p className="hero-lede">A focused starting point for an open, modern chess platform — built one reliable move at a time.</p><div className="hero-actions"><Link className="primary-button" href="/play">Explore the board <span>→</span></Link><a className="soft-button" href="#roadmap">See the roadmap</a></div><div className="hero-meta"><span><b>01</b> Next.js</span><span><b>02</b> Laravel API</span><span><b>03</b> Server authority</span></div></div><BoardPreview /></section><section className="feature-section page-width" id="learn"><div className="section-heading"><div><p className="eyebrow">THE OMEGA PROMISE</p><h2>Simple on the surface. Serious underneath.</h2></div><p>Phase 1 gives us the visual language, API boundary, and local workflow for everything that follows.</p></div><div className="feature-grid">{features.map((feature) => <article className="feature-card" key={feature.title}><span className="feature-icon">{feature.icon}</span><h3>{feature.title}</h3><p>{feature.text}</p></article>)}</div></section><section className="progress-section page-width" id="roadmap"><div className="progress-copy"><p className="eyebrow">A CLEAR PATH FORWARD</p><h2>From first move to full platform.</h2><p>We will build in runnable phases. No unfinished infrastructure will be hidden behind a pretty screen.</p></div><div className="roadmap"><div className="roadmap-item current"><span>01</span><div><strong>Foundation</strong><small>Now · Next.js · Laravel · SQLite</small></div><b>Now</b></div><div className="roadmap-item"><span>02</span><div><strong>Chess domain</strong><small>FEN · PGN · legal moves · game API</small></div></div><div className="roadmap-item"><span>03</span><div><strong>Live play</strong><small>Lobby · matchmaking · WebSocket</small></div></div></div></section><footer className="footer page-width"><span>OMEGA CHESS</span><p>Thoughtful chess for curious players.</p><span>© 2026</span></footer></main>;
}
